template = "https://github.com/giellalt/template-lang-und"
rev_id = 293
template_sha = "d22e247baeffac26e2fcc89a2b69592e66f6d04d"

[replacements]
__GLOTTOLOG_ID__ = "moks1248"
__REPO__ = "lang-mdf"
__UND2C__ = "mdf"
__UNDEFINED__ = "Moksha"
__UND__ = "mdf"
