template = "https://github.com/giellalt/template-lang-und"
rev_id = 323
template_sha = "dfd6613f16d25eef74b592360a48496624ab327d"

[replacements]
__GLOTTOLOG_ID__ = "moks1248"
__REPO__ = "lang-mdf"
__UND2C__ = "mdf"
__UNDEFINED__ = "Moksha"
__UND__ = "mdf"
